name: component-hiui
on: workflow_dispatch

jobs:
    build:
        name: Build ${{ matrix.arch }} ipk
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                arch:
                    - armvirt-64
                version: [22.03.0]

        steps:
            - uses: actions/checkout@v3

            - name: Build
              uses: innet8/gh-action-sdk@master
              env:
                  ARCH: ${{ matrix.arch }}-${{ matrix.version }}
                  MODE: all
                  FEEDNAME: hiui
                  PACKAGES: hiui-app-layout
                  V: s

            - name: Save Build Result
              uses: actions/upload-artifact@v2
              with:
                  name: ipk
                  path: |
                      hiui*.ipk
