name: hiui-glinet-release

on:
    push:
        tags:
            - '*'
jobs:
    build:
        name: Build ${{ matrix.arch }} ipk
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                arch:
                    - ipq_ipq40xx-qsdk11

        steps:
            - uses: actions/checkout@v3

            - run: echo "PKGS=$(ls $GITHUB_WORKSPACE/applications/|tr '\n' ' ')" >> $GITHUB_ENV

            - name: Build
              uses: innet8/gh-action-sdk@master
              env:
                  ARCH: ${{ matrix.arch }}
                  MODE: glinet
                  FEEDNAME: hiui
                  PACKAGES: hiui-rpc-core
                  CHECKS: no
                  V: s

            - name: Release and Upload Assets
              uses: softprops/action-gh-release@v1
              with:
                  files: 'hiui*.ipk'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
