name: build-hiui-glinet
on: workflow_dispatch

jobs:
    build:
        name: Build ${{ matrix.arch }} ipk
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                arch:
                    - ipq_ipq40xx-qsdk11

        steps:
            - uses: actions/checkout@v3

            - run: echo "PKGS=$(ls $GITHUB_WORKSPACE/applications/|tr '\n' ' ')" >> $GITHUB_ENV

            - name: Build
              uses: innet8/gh-action-sdk@master
              env:
                  ARCH: ${{ matrix.arch }}-${{ matrix.version }}
                  MODE: glinet
                  FEEDNAME: hiui
                  PACKAGES: hiui-ui-core hiui-rpc-core ${{env.PKGS}}
                  CHECKS: no
                  V: s

            - name: Save Build Result
              uses: actions/upload-artifact@v2
              with:
                  name: ipk
                  path: |
                      hiui*.ipk
